# Generated by Django 3.2.4 on 2021-09-12 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('select_type', models.CharField(choices=[('radio', 'Radio'), ('multi-select', 'Multi Select')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('event_type', models.CharField(choices=[('AS', 'Appearance or Signing'), ('AT', 'Attraction'), ('CT', 'Camp, Trip or Retreat'), ('CP', 'Concert or Performance'), ('CF', 'Conference'), ('CV', 'Convention'), ('CW', 'Course, Training or Workshop'), ('FF', 'Festival or Fair'), ('GC', 'Game or Competition'), ('MN', 'Meeting or Networking'), ('OT', 'Other'), ('PS', 'Party or Social Gathering'), ('RE', 'Race or Endurance Event'), ('RL', 'Rally'), ('SC', 'Screening'), ('ST', 'Seminar or Talk'), ('TR', 'Tour'), ('TT', 'Tournament'), ('TE', 'Tradeshow or Expo')], max_length=2)),
                ('category', models.CharField(choices=[('AB', 'Auto, Boat & Air'), ('BP', 'Business & Professional'), ('CC', 'Charities & Causes'), ('CO', 'Communities & Culture'), ('FE', 'Family & Education'), ('FB', 'Fashion & Beauty'), ('FM', 'Fild, Media & Entertainment'), ('FD', 'Food & Drink'), ('GP', 'Government & Politics'), ('HW', 'Health & Wellness'), ('HS', 'Hobbies & Special Interests'), ('HL', 'Home & Lifestyle'), ('MU', 'Music'), ('OT', 'Other'), ('PA', 'Performing & Visual Arts'), ('RS', 'Religion & Spirituality'), ('SA', 'School Activities'), ('ST', 'Science & Technology'), ('SE', 'Seasonal'), ('SF', 'Sports & Fitness'), ('TO', 'Travel & Outdoor')], max_length=2)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('contract_address', models.CharField(blank=True, max_length=128, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address_line1', models.CharField(blank=True, max_length=128, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('payment', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Donation', 'Donation')], default='Paid', max_length=64)),
                ('sale_start', models.DateTimeField()),
                ('sale_end', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('min_quantity', models.IntegerField(default=1)),
                ('max_quantity', models.IntegerField(default=10)),
                ('resale_permissions', models.CharField(choices=[('All', 'All'), ('None', 'None'), ('Custom', 'Custom')], default='None', max_length=64)),
                ('resale_wallets', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='TicketTypeAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.addon')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.tickettype')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AddOnOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.addon')),
            ],
        ),
        migrations.AddField(
            model_name='addon',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
