# Generated by Django 3.2.4 on 2021-09-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='addonoption',
            old_name='add_on',
            new_name='add_on_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='event',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='tickettypeaddon',
            old_name='add_on',
            new_name='add_on_id',
        ),
        migrations.RenameField(
            model_name='tickettypeaddon',
            old_name='ticket_type',
            new_name='ticket_type_id',
        ),
    ]
