# Generated by Django 3.2.4 on 2021-09-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210915_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='addonoption',
            old_name='add_on_id',
            new_name='add_on',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='tickettypeaddon',
            old_name='add_on_id',
            new_name='add_on',
        ),
        migrations.RenameField(
            model_name='tickettypeaddon',
            old_name='ticket_type_id',
            new_name='ticket_type',
        ),
    ]
