# Generated by Django 3.2.4 on 2021-10-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_addonoption_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('AB', 'Auto, Boat & Air'), ('BP', 'Business & Professional'), ('CC', 'Charities & Causes'), ('CO', 'Communities & Culture'), ('FE', 'Family & Education'), ('FB', 'Fashion & Beauty'), ('FM', 'Fild, Media & Entertainment'), ('FD', 'Food & Drink'), ('GP', 'Government & Politics'), ('HW', 'Health & Wellness'), ('HS', 'Hobbies & Special Interests'), ('HL', 'Home & Lifestyle'), ('MU', 'Music'), ('OT', 'Other'), ('PA', 'Performing & Visual Arts'), ('RS', 'Religion & Spirituality'), ('SA', 'School Activities'), ('ST', 'Science & Technology'), ('SE', 'Seasonal'), ('SF', 'Sports & Fitness'), ('TO', 'Travel & Outdoor')], default='MU', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Live', 'Live'), ('Started', 'Started'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=64),
        ),
    ]
