# Generated by Django 3.2.8 on 2022-02-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20220207_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='booking_addon',
            field=models.BooleanField(default=True),
        ),
    ]
