# Generated by Django 3.2.12 on 2022-02-19 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_addon_booking_addon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed ', 'Fixed Amount')], default='Percentage', max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='EventPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.promo')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='promos',
            field=models.ManyToManyField(through='events.EventPromo', to='events.Promo'),
        ),
    ]
