# Generated by Django 3.2.12 on 2022-02-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20220219_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='add_ons',
            field=models.ManyToManyField(related_name='TicketTypeAddOn', to='events.AddOn'),
        ),
    ]
