# Generated by Django 3.2.4 on 2021-09-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210915_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='size',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='published',
        ),
        migrations.AlterField(
            model_name='addonoption',
            name='add_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='events.addon'),
        ),
    ]
