# Generated by Django 3.2.4 on 2021-09-16 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210916_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='owner',
            new_name='organiser',
        ),
        migrations.AddField(
            model_name='event',
            name='changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='online_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='show_remaining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Live', 'Live'), ('Started', 'Started'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Live', max_length=64),
            preserve_default=False,
        ),
    ]
