# Generated by Django 3.2.4 on 2021-09-18 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='addonoption',
            name='price',
        ),
        migrations.AddField(
            model_name='addon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addon',
            name='max_quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='addon',
            name='min_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='addon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addon',
            name='sale_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addon',
            name='sale_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
