# Generated by Django 3.2.12 on 2022-02-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_tickettype_add_ons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='promos',
            field=models.ManyToManyField(blank=True, null=True, through='events.EventPromo', to='events.Promo'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='add_ons',
            field=models.ManyToManyField(blank=True, null=True, related_name='TicketTypeAddOn', to='events.AddOn'),
        ),
    ]
