# Generated by Django 3.2.4 on 2021-09-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnsBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('add_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.addon')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ticket')),
            ],
        ),
    ]
