# Generated by Django 3.2.4 on 2021-09-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_transaction_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonsbought',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='orders.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Purchased', 'Purchased'), ('Transferred', 'Transferred'), ('Expired', 'Expired')], max_length=64, null=True),
        ),
    ]
