# Generated by Django 3.2.8 on 2022-02-07 02:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20220207_0240'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_addonsbought_add_on_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Booking',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='transaction',
            new_name='booking',
        ),
    ]
