# Generated by Django 3.2.12 on 2022-02-19 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20220219_1941'),
        ('orders', '0008_auto_20220207_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromosRedeemed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=64)),
                ('redeemed', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.booking')),
                ('collection_promo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.collectioneventpromo')),
            ],
        ),
    ]
