# Generated by Django 3.2.12 on 2022-02-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220211_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nonce',
            field=models.CharField(default=123456, max_length=16),
            preserve_default=False,
        ),
    ]
