# Generated by Django 3.2.4 on 2021-09-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_addonoption_image'),
        ('orders', '0002_addonsbought'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
    ]
