# Generated by Django 3.2.4 on 2021-09-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210928_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Purchased', 'Purchased'), ('Transferred', 'Transferred'), ('Expired', 'Expired')], default='Purchased', max_length=64, null=True),
        ),
    ]
