# Generated by Django 3.2.8 on 2022-02-07 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20220207_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonsbought',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.booking'),
        ),
        migrations.AlterField(
            model_name='addonsbought',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='orders.ticket'),
        ),
    ]
