# Generated by Django 3.2.12 on 2022-02-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20220222_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='contract_address',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
