export const SET_PER_TICKET_AND_CUMULATIVE_ADDONS = "SET_PER_TICKET_AND_CUMULATIVE_ADDONS"
export const SET_FINAL_PER_TICKET_ADDONS = "SET_FINAL_PER_TICKET_ADDONS"

export const CLEAR_ADDONS = "CLEAR_ADDONS"